apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: toxicity

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: toxicity-api
    newName: docker.io/yourusername/toxicity-api
    newTag: 06f2fcf